### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by KillTheMule** [KillTheMule/nvim-rs#1]
- [ ] Figure out how plugins can quit

- [ ] Rewrite the API to be type save, and hide `rmpv::Value` from the user
  - Can probably be done for outgoing requests by recursively creating values
    - Fixed args are easy, but something like `nvim_call_function` probably needs going through a trait
  - Incoming Responses can be done like fixed args
  - Incoming Notifications/Requests might be impossible.
    - Check out `rmp-serde` or so, so maybe the user has to just declare a struct

- [ ] Consider error handling
  - Maybe get away from `Box<dyn Error>` in favor of a small enum?

- [ ] Can we merge `Requester` into `Neovim`? Could avoid doubling the API

- [ ] Need more tests
  - [ ]  Test all connection types on all OSes
  - [ ] Set up CI

- [ ] We need Tokio right now. What can we do to stay "as generic as possible", so we can move to other executors when the possibility arrives?
  - Use stuff from `futures` as far as possible.
  - See what we really need to expose from `crate::runtime`

- [ ] Consider public API.
  - Right now, everything's just the way it would compile

- [ ] Project management
  - [ ] README
  - [ ] COC
  - [ ] ...

- [ ] Check rust's API guidelines

**Comment by unrealhoang** [comment]
First, thank you for your effort of creating this project. I've also been discovering neovim rpc in Rust and `neovim-lib` was not satisfying enough.

For
> Rewrite the API to be type save, and hide rmpv::Value from the user
You can rely on rmpv::Value with `serde` feature and deserialize Value (or ValueRef) into user-defined struct. Your lib could also pre-define popular structs as well. Here is an example of me using in my project: 
https://github.com/unrealhoang/lspc/blob/master/src/neovim.rs#L301-L312

**Comment by KillTheMule** [comment]
Ahh very cool, I was hoping for something like this. Seems like it's an achievable goal to hide `Value` from the user :) Thanks!

**Comment by thjbdvlt** [comment]
@KillTheMule  As I'm developping a Neovim GUI using nvim-rs, I'd like to contribute to the project (I've already submit a very-minimal-now-merged one-line-PR). Is this roadmap still the place to look for things to be done?

**Comment by KillTheMule** [comment]
Hey thanks for your interest! I've not been able to put enough time into this, unfortunately, so you're very right to ask :)

The list probably hasn't aged very well, I need to go through it and investigate things a bit. I've in particular soured about the strongly-typed API (if we can't do it consistently, we should probably just forego it; consistency _is_ a value of its own in a library). But some others are even unclear to me now :grin:

If you want to get going, there are several things that are needed anyways:

- Update to latest neovim release
- Check if we can/should support other runtimes (I've some glib code lying around I could brush up, and https://github.com/KillTheMule/nvim-rs/issues/55 is still relevant ... maybe others have arisen now?)
- https://github.com/KillTheMule/nvim-rs/issues/54 is still relevant
-  On a higher level: Could we reasonably offer a single-threaded API, i.e. doing away with `Send` and `Sync`?

I'll go through the "larger" roadmap and update it soon, I'll let you know via this issue :)

**Comment by KillTheMule** [comment]
Ok, I've updated the roadmap, if you've further questions let me know.

**Comment by thjbdvlt** [comment]
@KillTheMule Thank's for your answers and the update! I'll check what I can do :)
